# -*- coding: utf-8 -*-
"""Euclides.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hIXGJY_i_SanQQZV6rytevs9OBocWDJz
"""

# Jaiber Duvan Diaz León - 20222020011
# Rosa Alejandra López Lizarazo - 20222020134
# Andrés Nicolas Mendoza Silva - 20222020152


#Paso por valor: Se crea una copia del valor que se pasa, y esta copia se utiliza en la función.
#Los cambios realizados en la copia no afectan el valor original.
#Paso por referencia: Se pasa una referencia al valor original, no una copia.
#Esto significa que si cambias el valor en la función, también cambiará el valor original.


def euclides_por_valor(a, b):
    while b != 0:
        a, b = b, a % b
    return a

def euclides_por_referencia(valores):
    a, b = valores[0], valores[1]
    while b != 0:
        a, b = b, a % b
    valores[0] = a
    valores[1] = b
    return valores[0]

# Entrada de los números
num1 = int(input("Introduce el primer número: "))
num2 = int(input("Introduce el segundo número: "))

# Calculo del MCD por valor
resultado_valor = euclides_por_valor(num1, num2)
print(f"El MCD de {num1} y {num2} por valor es: {resultado_valor}")

# Calculo del MCD por referencia
valores = [num1, num2]
resultado_referencia = euclides_por_referencia(valores)
print(f"El MCD de {num1} y {num2} por referencia es: {resultado_referencia}")